services:
  strom:
    image: eyevinntechnology/strom:0.4.2
    container_name: strom
    network_mode: host
    privileged: true
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    volumes:
      - ./data:/data
      - ./target/debug/strom:/app/strom
    command: ["/app/strom", "--headless"]