#!/bin/bash

# Remove STROM_DATABASE_URL if it's empty or contains only whitespace
if [ -z "${STROM_DATABASE_URL## }" ]; then
    unset STROM_DATABASE_URL
fi

# Execute the command passed to the container
exec "$@"
